version: "3.4"

networks:
  web-app:
    driver: bridge

services:
  posts_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "posts_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - web-app
volumes:
  app-data: